// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

export type DetectAccentDetectAccentPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/detect-accent';
};

export type DetectAccentDetectAccentPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
